# Generated by Django 5.1.6 on 2025-02-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_booking_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('comment', models.TextField(verbose_name='Сообщение')),
            ],
        ),
    ]
