# Generated by Django 5.1.6 on 2025-02-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=1, verbose_name='Телефон'),
        ),
    ]
