# Generated by Django 5.1.6 on 2025-02-20 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0009_alter_feedback_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databooking',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
    ]
