# Generated by Django 5.1.6 on 2025-02-28 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0011_apartmentphoto_alter_apartment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='street',
            field=models.TextField(blank=True, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='за сутки', max_digits=12, verbose_name='Цена'),
        ),
    ]
